### ISSUE TITLE
Data inconsistente

### ISSUE THREAD

**Issue by devildeveloper** [jhersonos/Pedido#3]
Al hacer click en el boton +producto ( agregar producto ) este se muestra vacio si no hay data que mostar, ya que no se ha seleccionado una sede. 
Ese boton debería estar bloqueado hasta que se seleccione una sede
![captura de pantalla 2016-11-17 a las 5 11 21 p m](https://cloud.githubusercontent.com/assets/2333365/20410013/1d9e7eec-ace9-11e6-9989-72a9d7544b06.png)

**Comment by jhersonos** [comment]
complete in the second issues close
